sudo: required

language: java

jdk:
  - oraclejdk8

os:
  - linux

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
before_install:
 - chmod +x gradlew

script:
  - pwd
  - ls -a
  - env
  - echo '88888' > test.log
  - ls -a
